name: CI build

# See
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
# for why this workflow is required
on:
  pull_request:
    branches:
    - main
    paths:              # Ensure that the trigger paths are the inverse of those in ci.yml
    - docs/**
  workflow_dispatch:    # Allow running the workflow manually from the GitHub UI

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No build required"'